### ISSUE TITLE
Document not loading.

### ISSUE THREAD

**Issue by LohithAnand** [kogmbh/WebODF#586]
I am using webodf for providing preview option for odf file in my web application.
Everything worked fine locally but in my live server odf failed to load the documents. 

Javascript console logs :
WARNING: refreshOdf called but ODF was not DONE.        (webodf.js line 44)
will be back later...                                                                (webodf.js line 44)

will be back later.. will be logged every second but the document never loads

Webserver run apache2

**Comment by kossebau** [comment]
Thanks for telling how your problem was resolved. This actually might show a bug in WebODF where gzip responses from the server when requesting the document should be avoided (both because ODF files are zip archives already, unless flat, and because the code does not handle that). Opened explicitely as #858. So closing this one here as solved.
